name: Java CI/CD Container Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Self-Contained Docker Image
      run: |
        IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
        
        docker build \
          -t $IMAGE_NAME:latest \
          -t $IMAGE_NAME:${{ github.sha }} .
          
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:${{ github.sha }}